import {PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT} from "../index"

export const SLUG_APP_PAGE_SECURE_ACCOUNT_CURRENT_SIGN_OUT = "sign-out/"
export const PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT_SIGN_OUT = `${PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT}${SLUG_APP_PAGE_SECURE_ACCOUNT_CURRENT_SIGN_OUT}`
