import {PATH_APP_PAGE_SECURE_ACCOUNT_GUEST} from "../index"

export const SLUG_APP_PAGE_SECURE_ACCOUNT_GUEST_SIGN_IN = "sign-in/"
export const PATH_APP_PAGE_SECURE_ACCOUNT_GUEST_SIGN_IN = `${PATH_APP_PAGE_SECURE_ACCOUNT_GUEST}${SLUG_APP_PAGE_SECURE_ACCOUNT_GUEST_SIGN_IN}`
