import {PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT} from "../index"

export const SLUG_APP_PAGE_SECURE_ACCOUNT_CURRENT_PICTURE = "picture/"
export const PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT_PICTURE = `${PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT}${SLUG_APP_PAGE_SECURE_ACCOUNT_CURRENT_PICTURE}`
