import {PATH_APP_PAGE_SECURE_SHELTER} from "../index"

export const SLUG_APP_PAGE_SECURE_SHELTER_DASHBOARD = "dashboard/"
export const PATH_APP_PAGE_SECURE_SHELTER_DASHBOARD = `${PATH_APP_PAGE_SECURE_SHELTER}${SLUG_APP_PAGE_SECURE_SHELTER_DASHBOARD}`
