import {PATH_APP_PAGE_SECURE_ACCOUNT_GUEST} from "../index"

export const SLUG_APP_PAGE_SECURE_ACCOUNT_GUEST_FORGOT_PASSWORD = "forgot-password/"
export const PATH_APP_PAGE_SECURE_ACCOUNT_GUEST_FORGOT_PASSWORD = `${PATH_APP_PAGE_SECURE_ACCOUNT_GUEST}${SLUG_APP_PAGE_SECURE_ACCOUNT_GUEST_FORGOT_PASSWORD}`
