import {PATH_APP_PAGE_SECURE_SHELTER} from "../index"

export const SLUG_APP_PAGE_SECURE_SHELTER_PET = "pet/"
export const PATH_APP_PAGE_SECURE_SHELTER_PET = `${PATH_APP_PAGE_SECURE_SHELTER}${SLUG_APP_PAGE_SECURE_SHELTER_PET}`
