import {PATH_APP_PAGE_GUEST_ERROR} from "../index"

export const SLUG_APP_PAGE_GUEST_ERROR_404 = "404/"
export const PATH_APP_PAGE_GUEST_ERROR_404 = `${PATH_APP_PAGE_GUEST_ERROR}${SLUG_APP_PAGE_GUEST_ERROR_404}`
