import {PATH_APP_PAGE_SECURE_ACCOUNT} from "../index"

export const SLUG_APP_PAGE_SECURE_ACCOUNT_CURRENT = "current/"
export const PATH_APP_PAGE_SECURE_ACCOUNT_CURRENT = `${PATH_APP_PAGE_SECURE_ACCOUNT}${SLUG_APP_PAGE_SECURE_ACCOUNT_CURRENT}`
