import {PATH_APP_PAGE_SECURE_ACCOUNT} from "../index"

export const SLUG_APP_PAGE_SECURE_ACCOUNT_GUEST = "guest/"
export const PATH_APP_PAGE_SECURE_ACCOUNT_GUEST = `${PATH_APP_PAGE_SECURE_ACCOUNT}${SLUG_APP_PAGE_SECURE_ACCOUNT_GUEST}`
